### ISSUE TITLE
OnBackPressed  is not handled.

### ISSUE THREAD

**Issue by Anant00** [sidhuparas/Coronavirus-Tracker#3]
Problem: App does NOT exit when pressed back button in Overview fragment. 

```
fun handleBackPress(): Boolean {
        if (`searchEditText.isVisible`) {
            showSearch(false)
            return true
        }

        return false
    }
```

**This method inside Overview Fragment always returns true.**

Therefore,

```
override fun onBackPressed() {
        if (activeFragment == overviewFragment) {
            if (overviewFragment.handleBackPress()) {

            } else {
                finish()
            }
        } else if (activeFragment == indiaFragment) {
            handleOverviewAction()
        } else {
            super.onBackPressed()
        }
    }
```

The above method does not do anything. 

To solve this, 
`searchEditText.isVisible` should be changed to `searchEditText.isFocused`

I think the problem is that inside **overview_fragment.xml** the searchEditText is always visible, as it doesn't have  `android:visibility="invisible"` before user clicks on search icon. It always is visible.

Another ways to fix this. 
Make searchEditText visible and invisible to make `searchEditText.isVisible`  work.
Or, since searchBar already has `android:visibility="gone"`, it would work perfectly fine. 
Replace `searchEditText.isVisible`. with just `searchBar.isVisible
`

**Comment by sidhuparas** [comment]
Fixed it in https://github.com/sidhuparas/Coronavirus-Tracker/commit/e32de61c34dca1e454d5a72923bef72453baa0ea.
